### ISSUE TITLE
progressbar_demo.c not in pure c99, should be built with -std=gnu99

### ISSUE THREAD

**Issue by joshua5201** [doches/progressbar#5]
as the title, but I think this is not really important, though.

test/progressbar_demo.c: In function ‘main’:
test/progressbar_demo.c:49:9: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
         usleep(SLEEP_US);                                                      
         ^

**Comment by kirbyfan64** [comment]
I believe you can also define `_BSD_SOURCE` to fix that.

**Comment by doches** [comment]
I can't recreate this on OS X, the following build commands:

    gcc -c -std=c99 -Iinclude -Wimplicit-function-declaration -Wall -Wextra -pedantic lib/progressbar.c
    gcc -c -std=c99 -Iinclude -Wimplicit-function-declaration -Wall -Wextra -pedantic test/progressbar_demo.c
    gcc -c -std=c99 -Iinclude -Wimplicit-function-declaration -Wall -Wextra -pedantic lib/statusbar.c
    gcc -std=c99 -Iinclude -Wimplicit-function-declaration -Wall -Wextra -pedantic progressbar.o statusbar.o progressbar_demo.o -lncurses -o demo

produce no errors or warnings, specifically not the one you mention above. What's your build environment?

**Comment by nibroc** [comment]
I get a similar warning on Ubuntu.

I suspect that due to Mac's BSD lineage, `usleep` is exported in `unistd.h` by default, but in libc, `usleep` is exposed if BSD features are enabled or POSIX features are enabled.

To this end, I think setting `_XOPEN_SOURCE` to `500` is likely the best option. That will mean that the demo program will compile on any system is that both C99 and POSIX 1995 compliant. Also, if you split out the compile flags for the main library, you could keep it pure C99 and then just require POSIX for the demo.

It might also be worth mentioning that `_BSD_SOURCE` is deprecated and will start spitting out warnings in newer versions of libc. `_DEFAULT_SOURCE` is intended to replace it, though it covers more than just `_BSD_SOURCE` alone.
